workflow:
    name: Solar System NodeJS Pipeline
    # WE CAN ALSO DEFINE RULES AT WORKFLOW LEVEL (WILL WORK ON IT LATER)

# VARIABLES ARE STORED AS A PROTECTED/MASKED VARIABLES IN GITLAB UI: GitLab UI -> Settings -> CICD -> variables
variables:
  MONGO_URI: $MONGODB_URI
  MONGO_USERNAME: $MONGODB_USERNAME 
  MONGO_PASSWORD: $$MONGODB_PASSWORD
  IMAGE_VERSION: $CI_PIPELINE_ID
  DOCKER_USERNAME: $MY_DOCKER-USERNAME
  DOCKER_PASSWORD: $MY_DOCKER_PASSWORD
  DOCKER_REGISTRY: $MY_DOCKER_REGISTRY
  IMAGE_NAME: "$MY_DOCKER_REGISTRY/root/$CI_PROJECT_NAME"
  IMAGE_TAG: "$CI_COMMIT_SHA"
  K8S_IMAGE: $DOCKER_USERNAME/solar-system:$IMAGE_VERSION
  REPLICAS: 2
  NAMESPACE: Development

stages: # WE DEFINE STAGES T0 LOGICALLY GROUP THE JOBS. JOBS DEFINED IN SAME STAGE RUNS IN PARALLEL UNLESS USED NEEDS KEYWORD 
  - test
  - containerization
  - deploy
  
unit_testing:
  stage: test
  image: node:17-alpine3.14
  before_script:
    - npm install
  script:
    - npm test
  cache:    # WE USE CACHE KEYWORD SO THAT DEPENDENCIES INSTALLED IN ONE JOB CAN BE USED IN OTHER JOBS WITHOUT THEM DOWNLOADING AGAIN
    policy: pull-push
    key:
        files:
          - package-lock.json
        prefix: node-modules
    paths:
      - node_modules
  artifacts:           # WE STORE THE ARTIFACTS, SO THAT THEY CAN BE USED IN DIFFERENT JOBS SINCE JOBS MIGHT RUN ON DIFFERENT MACHINES.
    name: Mocha-Test-Result
    when: on_success
    paths:
      - test-results.xml
    expire_in: 3 days 

code_coverage:
  stage: test
  image: node:17-alpine3.14
  before_script:
    - npm install
  cache:
    policy: pull
    key:
        files:
          - package-lock.json
        prefix: node-modules
    paths:
      - node_modules
  script: |
    npm run coverage
  artifacts:
    name: Code-Coverage-Result
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
  allow_failure: true # IF WE SET THIS PARAMETER THEN EVEN IF THE JOB FAILS, PIPELINE WILL NOT FAIL

docker_build:
  stage: containerization
  image: docker:24.0.5
  dependencies: []             # YOU DON'T WANT THIS JOB TO DOWNLOAD ANY ARTIFACTS FROM THE PREVIOUS JOBS, THAT'S WAY [].
  services:
    - docker:24.0.5-dind  # SINCE WE ARE RUNNING DOCKER COMMAND IN DOCKER (BECAUSE WE ARE USING DOCKER AS OUR EXECUTER IN THIS CASE) WE USE THIS SERVICE
  script:
    - docker build -t $DOCKER_USERNAME/solar-system:$IMAGE_VERSION .
    - docker images $DOCKER_USERNAME/solar-system:$IMAGE_VERSION
    - mkdir image
    - docker save $DOCKER_USERNAME/solar-system:$IMAGE_VERSION > image/solar-system-image:$IMAGE_VERSION.tar
  artifacts:
    when: on_success
    paths:
      - image
    expire_in: 3 days 

docker_test:
  stage: containerization
  image: docker:24.0.5
  needs:
    - docker_build             
  services:
    - docker:24.0.5-dind
  script:
    - docker Load -i image/solar-system-image-$CI_PIPELINE_ID.tar
    - docker run --name solar-system-app -d -p 3000:3000 $DOCKER_USERNAME/solar-system:$IMAGE_VERSION
    - export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
    - echo $IP
    - docker run alpine wget -q -O - http://$IP:3000/Live| grep Live

docker_push:
  stage: containerization
  needs:
    - docker_build 
    - docker_test
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - docker Load -i image/solar-system-image-$CI_PIPELINE_ID.tar
    - docker login --username=$DOCKER_USERNAME --password=DOCKER_PASSWORD
    - docker push $DOCKER_USERNAME/solar-system:$IMAGE_VERSION


k8s_connect_deploy:
  stage: deploy
  image: ubuntu:22.04
  dependencies: []
  before_script: 
    - apt update    
    - apt install -y curl
    - curl -LO "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - apk add --no-cache gettext
    - envsubst -V
  script:
    - export KUBECONFIG=$KUBE_CONFIG  
    - kubectl version -o yaml
    - kubectl config get-contexts
    - kubectl get nodes    
    - export INGRESS_IP=$(kubectl -n ingress-nginx get services ingress-nginx-controller -O jsonpath="{.status.loadBalancer.ingress[0].ip}")
    - echo $INGRESS_IP
    - kubectl -n "$NAMESPACE" create secret generic mongo-db-creds --from-literal=MONGO_URI="$MONGO_URI" --from-literal=MONGO_USERNAME="$MONGO_USERNAME" --from-literal=MONGO_PASSWORD="$MONGO_PASSWORD" --save-config --dry-run=client -o yaml | kubectl apply -f -
    - for i in kubernetes/manifest/*.yaml; do envsubst < $i | kubectl apply -f -; done
    - kubectl -n $NAMESPACE get all 
    - echo "INGRESS_URL=$(kubectl -n $NAMESPACE get ing -o jsonpath="{.items[0].spec.tls[0].hosts[0]}")" >> app_ingress_url.env
  artifacts:
  reports:
    dotenv: app_ingress_url.env

k8s_ntegration_testing:
  stage: deploy
  image: alpine:3.7
    needs:
    - k8s_connect_deploy
  before_script:
    - apk --no-cache add curl
    - apk --no-cache add jq
  script:
    - echo $INGRESS_URL
    - curl -s -k https://$INGRESS_URL/live | jq -r .status | grep -i live
    - curl -s -k https://$INGRESS_URL/ready | jq -r .status | grep -i ready
